os: Visual Studio 2015

platform:
  - x64

configuration:
  - Release
  - Debug

environment:
  DEPENDENCIES_FOLDER: 'C:\projects\dependencies'
  DOWNLOADS_FOLDER: 'C:\projects\downloads'

  matrix:
    - MSVC_VERSION: '14.0'
      RUNTIME_LINKAGE: 'static'
      PCRE_VERSION: '8.42'
      OPENSSL_VERSION: '1.0.2l'

cache:
  - C:\projects\downloads -> .appveyor.yml
  - C:\projects\dependencies -> .appveyor.yml

install:
  - ps: |
      $env:WINDOWS_SDK_ENV_BATCH_FILE = ""
      $env:WINDOWS_SDK_ENV_PARAMETERS = ""
      $env:MSVS_HOME = "${env:ProgramFiles(x86)}\Microsoft Visual Studio $env:MSVC_VERSION"
      $env:VCVARS_BATCH_FILE = "$env:MSVS_HOME\VC\vcvarsall.bat"
      switch ($env:PLATFORM) {
        "Win32" {
          $env:VCVARS_PLATFORM = "x86"
        }
        "x64" {
          switch ($env:MSVC_VERSION) {
            "14.0" {
              $env:VCVARS_PLATFORM = "amd64"
            }
            "12.0" {
              $env:VCVARS_PLATFORM = "amd64"
            }
            "11.0" {
              $env:VCVARS_PLATFORM = "x86_amd64"
            }
            "10.0" {
              $env:VCVARS_BATCH_FILE = ""
              $env:WINDOWS_SDK_ENV_BATCH_FILE = "$env:ProgramFiles\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd"
              $env:WINDOWS_SDK_ENV_PARAMETERS = "/x64 /$env:CONFIGURATION"
            }
            default {
              throw "Unsupported MSVS version: $env:MSVC_VERSION"
            }
          }
        }
        default {
          throw "Unsupported platform: $env:PLATFORM"
        }
      }
      if ($env:PCRE_VERSION) {
        $pcre_platform_suffix = ""
        switch ($env:PLATFORM) {
          "Win32" {
            $pcre_platform_suffix = "-x86"
          }
          "x64" {
            $pcre_platform_suffix = "-x64"
          }
          default {
            throw "Unsupported platform for pre-built PCRE: $env:PLATFORM"
          }
        }
        $pcre_version_suffix = "-$env:PCRE_VERSION"
        $pcre_toolchain_suffix = ""
        switch ($env:MSVC_VERSION) {
          "14.0" {
            $pcre_toolchain_suffix = "-vs2015"
          }
          default {
            throw "Unsupported MSVS version for pre-built PCRE: $env:MSVC_VERSION"
          }
        }
        $pcre_install_folder = "$env:DEPENDENCIES_FOLDER\pcre$pcre_version_suffix$pcre_platform_suffix$pcre_toolchain_suffix"
        if (!(Test-Path -Path "$pcre_install_folder")) {
          Write-Host "Built PCRE libraries are absent for the selected toolchain (msvc-$env:MSVC_VERSION) and PCRE version ($env:PCRE_VERSION)"
          $pcre_archive_name = "pcre$pcre_version_suffix$pcre_platform_suffix$pcre_toolchain_suffix.7z"
          $pcre_archive_file = "$env:DOWNLOADS_FOLDER\$pcre_archive_name"
          if (!(Test-Path -Path "$pcre_archive_file")) {
            $pcre_download_url = "https://dl.bintray.com/mabrarov/generic/pcre/$env:PCRE_VERSION/$pcre_archive_name"
            if (!(Test-Path -Path "$env:DOWNLOADS_FOLDER")) {
              New-Item "$env:DOWNLOADS_FOLDER" -type directory | out-null
            }
            Write-Host "Going to download pre-built PCRE libraries from: $pcre_download_url to: $pcre_archive_file"
            curl.exe --connect-timeout 300 --max-time 1800 --show-error --silent --location --output "$pcre_archive_file" "$pcre_download_url"
            if ($LastExitCode -ne 0) {
              throw "Downloading of pre-built PCRE libraries failed with exit code $LastExitCode."
            }
            Write-Host "Downloaded pre-built PCRE libraries: $pcre_archive_file"
          }
          Write-Host "Extracting pre-built PCRE libraries from: $pcre_archive_file to: $env:DEPENDENCIES_FOLDER"
          if (!(Test-Path -Path "$env:DEPENDENCIES_FOLDER")) {
            New-Item "$env:DEPENDENCIES_FOLDER" -type directory | out-null
          }
          7z.exe x "$pcre_archive_file" -o"$env:DEPENDENCIES_FOLDER" -aoa -y | out-null
          if ($LastExitCode -ne 0) {
            throw "File extraction failed with exit code $LastExitCode."
          }
          Write-Host "Extracted: $pcre_install_folder"
        }
        $env:PCRE_ROOT = "$pcre_install_folder"
      }
      if ($env:OPENSSL_VERSION) {
        $openssl_platform_suffix = ""
        switch ($env:PLATFORM) {
          "Win32" {
            $openssl_platform_suffix = "x86"
          }
          "x64" {
            $openssl_platform_suffix = "x64"
          }
          default {
            throw "Unsupported platform for pre-built OpenSSL: $env:PLATFORM"
          }
        }
        $openssl_version_suffix = "-$env:OPENSSL_VERSION"
        $openssl_toolchain_suffix = ""
        switch ($env:MSVC_VERSION) {
          "14.0" {
            $openssl_toolchain_suffix = "-vs2015"
          }
          default {
            throw "Unsupported MSVS version for pre-built OpenSSL: $env:MSVC_VERSION"
          }
        }
        $openssl_platform_install_folder = "$env:DEPENDENCIES_FOLDER\$openssl_platform_suffix"
        $openssl_install_folder = "$openssl_platform_install_folder\openssl$openssl_version_suffix$openssl_toolchain_suffix"
        if (!(Test-Path -Path "$openssl_install_folder")) {
          Write-Host "Built OpenSSL libraries are absent for the selected toolchain (msvc-$env:MSVC_VERSION) and OpenSSL version ($env:OPENSSL_VERSION)"
          $openssl_archive_name = "openssl$openssl_version_suffix$openssl_toolchain_suffix.7z"
          $openssl_archive_file = "$env:DOWNLOADS_FOLDER\$openssl_archive_name"
          if (!(Test-Path -Path "$openssl_archive_file")) {
            $openssl_download_url = "https://www.npcglib.org/~stathis/downloads/$openssl_archive_name"
            if (!(Test-Path -Path "$env:DOWNLOADS_FOLDER")) {
              New-Item "$env:DOWNLOADS_FOLDER" -type directory | out-null
            }
            Write-Host "Going to download pre-built OpenSSL libraries from: $openssl_download_url to: $openssl_archive_file"
            curl.exe --connect-timeout 300 --max-time 1800 --show-error --silent --location --output "$openssl_archive_file" "$openssl_download_url"
            if ($LastExitCode -ne 0) {
              throw "Downloading of pre-built OpenSSL libraries failed with exit code $LastExitCode."
            }
            Write-Host "Downloaded pre-built OpenSSL libraries: $openssl_archive_file"
          }
          Write-Host "Extracting pre-built OpenSSL libraries from: $openssl_archive_file to: $openssl_platform_install_folder"
          if (!(Test-Path -Path "$openssl_platform_install_folder")) {
            New-Item "$openssl_platform_install_folder" -type directory | out-null
          }
          7z.exe x "$openssl_archive_file" -o"$openssl_platform_install_folder" -aoa -y | out-null
          if ($LastExitCode -ne 0) {
            throw "File extraction failed with exit code $LastExitCode."
          }
          Write-Host "Extracted: $openssl_install_folder"
          Write-Host "Re-organizing OpenSSL directories..."
          $openssl_directories_to_change = @("lib", "include", "bin")
          foreach ($openssl_directory_to_change in $openssl_directories_to_change) {
            switch ($env:PLATFORM) {
              "Win32" {
                $openssl_directory_to_remove = "${openssl_directory_to_change}64"
                Write-Host "Removing directory: $openssl_directory_to_remove"
                Remove-Item -Path "$openssl_directory_to_remove" -Recurse -Force
              }
              "x64" {
                $openssl_directory_to_rename = "${openssl_directory_to_change}64"
                Write-Host "Removing directory: $openssl_directory_to_change"
                Remove-Item -Path "$openssl_directory_to_change" -Recurse -Force
                Write-Host "Renaming directory $openssl_directory_to_rename to $openssl_directory_to_change"
                Rename-Item -Path "$openssl_directory_to_rename" -NewName "$openssl_directory_to_change" -Force
              }
              default {
                throw "Unsupported platform for pre-built OpenSSL: $env:PLATFORM"
              }
            }
          }
          Write-Host "... successfully completed re-organization of OpenSSL directories."
        }
        $env:OPENSSL_ROOT = "$openssl_install_folder"
      }
      switch ($env:CONFIGURATION) {
        "Debug" {
          $env:CMAKE_BUILD_CONFIG = "DEBUG"
        }
        "Release" {
          $env:CMAKE_BUILD_CONFIG = "RELEASE"
        }
        default {
          throw "Unsupported build configuration: $env:CONFIGURATION"
        }
      }
      $cmake_generator_msvc_version_suffx = " $env:MSVC_VERSION" -replace "([\d]+)\.([\d]+)", '$1'
      switch ($env:MSVC_VERSION) {
        "14.0" {
          $cmake_generator_msvc_version_suffx = "$cmake_generator_msvc_version_suffx 2015"
        }
        "12.0" {
          $cmake_generator_msvc_version_suffx = "$cmake_generator_msvc_version_suffx 2013"
        }
        "11.0" {
          $cmake_generator_msvc_version_suffx = "$cmake_generator_msvc_version_suffx 2012"
        }
        "10.0" {
          $cmake_generator_msvc_version_suffx = "$cmake_generator_msvc_version_suffx 2010"
        }
        "9.0" {
          $cmake_generator_msvc_version_suffx = "$cmake_generator_msvc_version_suffx 2008"
        }
        default {
          throw "Unsupported MSVS version: $env:MSVC_VERSION"
        }
      }
      $cmake_generator_platform_suffix = ""
      switch ($env:PLATFORM) {
        "Win32" {
          $cmake_generator_platform_suffix = ""
        }
        "x64" {
          $cmake_generator_platform_suffix = " Win64"
        }
        default {
          throw "Unsupported platform: $env:PLATFORM"
        }
      }
      $env:CMAKE_GENERATOR = "Visual Studio$cmake_generator_msvc_version_suffx$cmake_generator_platform_suffix"

before_build:
  - ps: |
      Write-Host "PLATFORM                  : $env:PLATFORM"
      Write-Host "CONFIGURATION             : $env:CONFIGURATION"
      Write-Host "WINDOWS_SDK_ENV_BATCH_FILE: $env:WINDOWS_SDK_ENV_BATCH_FILE"
      Write-Host "WINDOWS_SDK_ENV_PARAMETERS: $env:WINDOWS_SDK_ENV_PARAMETERS"
      Write-Host "VCVARS_BATCH_FILE         : $env:VCVARS_BATCH_FILE"
      Write-Host "VCVARS_PLATFORM           : $env:VCVARS_PLATFORM"
      Write-Host "APPVEYOR_BUILD_FOLDER     : $env:APPVEYOR_BUILD_FOLDER"
      if ($env:PCRE_ROOT) {
        Write-Host "PCRE_ROOT                 : $env:PCRE_ROOT"
      }
      if ($env:OPENSSL_ROOT) {
        Write-Host "OPENSSL_ROOT              : $env:OPENSSL_ROOT"
      }
      Write-Host "CMAKE_GENERATOR           : $env:CMAKE_GENERATOR"
  - cmd: if not "%WINDOWS_SDK_ENV_BATCH_FILE%"=="" call "%WINDOWS_SDK_ENV_BATCH_FILE%" %WINDOWS_SDK_ENV_PARAMETERS%
  - cmd: if not "%VCVARS_BATCH_FILE%"=="" call "%VCVARS_BATCH_FILE%" %VCVARS_PLATFORM%

build_script:
  - ps: |
      New-Item "$env:APPVEYOR_BUILD_FOLDER\build\cmake\build" -type directory | out-null
      Set-Location -Path "$env:APPVEYOR_BUILD_FOLDER\build\cmake\build"
      cmake -D CMAKE_USER_MAKE_RULES_OVERRIDE=$env:APPVEYOR_BUILD_FOLDER\build\cmake\cmake\static_c_runtime_overrides.cmake -D CMAKE_USER_MAKE_RULES_OVERRIDE_CXX=$env:APPVEYOR_BUILD_FOLDER\build\cmake\cmake\static_cxx_runtime_overrides.cmake -D PCRE_ROOT=$env:PCRE_ROOT -D OPENSSL_ROOT_DIR=$env:OPENSSL_ROOT -G "$env:CMAKE_GENERATOR" $env:APPVEYOR_BUILD_FOLDER\build\cmake
      if ($LastExitCode -ne 0) {
        throw "Generation of project failed with exit code $LastExitCode."
      }
      $build_cmd = "cmake --build . --config $env:CONFIGURATION"
      if ($env:MSVC_VERSION -ne "9.0") {
        $build_cmd = "$build_cmd -- /maxcpucount /verbosity:normal /logger:""C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"""
      }
      Invoke-Expression "$build_cmd"
      if ($LastExitCode -ne 0) {
        throw "Build failed with exit code $LastExitCode."
      }

artifacts:
  - path: build\cmake\build\zabbix_agent\$(configuration)\*.exe
    name: zabbix_agent
